development:
  cloud_name: ngocnguyen
  api_key: 'yourkey'
  api_secret: yourkey
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ngocnguyen
  api_key: 'yourkey'
  api_secret: yourkey
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ngocnguyen
  api_key: 'yourkey'
  api_secret: yourkey
  enhance_image_tag: true
  static_image_support: false
